config/routes.rb
Rails.application.routes.draw do

  resources :friend_requests, only: [:create, :update, :destroy]
  resources :posts
  resources :comments, only: [:create]

  devise_for :user, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/users/all', to: 'user#all', as: :find_friends
  get '/users/:id', to: 'user#show', as: :user
  get '/users/:id/edit', to: 'user#edit', as: :edit_user
  get '/users/:id/friends', to: 'friends#index', as: :friends
  delete '/users/:id/friends', to: 'friends#destroy', as: :remove_friend

  post '/posts/like', to: 'likes#create', as: :like_post
  delete '/posts/:id/unlike', to: 'likes#destroy', as: :unlike_post

  get '/friend_requests/', to: 'friend_requests#index', as: :requests

  get '/privacy_policy', to: 'static_pages#privacy', as: :privacy

  match "*path", to: "application#render_404", via: :all

  devise_scope :user do
    authenticated :user do
      root 'static_pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: { maximum: 50 }
  validates :bio, length: { maximum: 300 }

  has_many :posts
  has_many :notifications
  has_many :likes
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friends

  def remove_friend
    current_user.friends.destroy(friend)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def all
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :firstname, :lastname])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def others
    users = User.where.not(id: current_user.id)
  end

  def get_friend_request(user_id)
    FriendRequest.where("user_id = ? AND friend_id = ?", current_user.id, user_id).first || FriendRequest.new
  end
end

app/views/user/all.html.erb
<div class="container friends-container">
  <div class="row">
    <% others.each do |user| %>
      <div class="col-md-3">
        <div class="card">
          <%= link_to user_path(user.id) do %>
            <img src="http://via.placeholder.com/250x250" alt="">
            <h3><%= "#{user.firstname} #{user.lastname}" %></h3>
          <% end %>

          <% friend_request = get_friend_request(user.id) %>
          
          <% if policy(friend_request).create? %>
          <%= link_to "Send Request", friend_requests_path(friend_id: user.id), method: :post, class: "btn btn-primary" %>
          <% end %>

          <% if policy(friend_request).destroy? %>
          <%= link_to "Cancel Request", friend_request_path(id: user.id), method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user/edit.html.erb
<div class="edit-profile-container container">

    <form>
      <div class="form-row">
        <div class="col-md-3">
          <img class="avatar" src="http://via.placeholder.com/48x48" alt="avatar">
        </div>
        <div class="col-md-9">
          <div class="form-group">
            <input type="text" name="firstname" class="form-control" placeholder="First Name">
          </div>
          <div class="form-group">
            <input type="text" name="lastname" class="form-control" placeholder="Last Name">
          </div>
          <div class="form-group">
            <input type="email" name="email" class="form-control" placeholder="emailaddress@gmail.com">
          </div>
        </div>
      </div>

      <div class="form-row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="bio">Write something about yourself</label>
            <textarea class="form-control" id="bio" rows="7"></textarea>
          </div>
          <button class="btn btn-success pull-right" type="submit">Save Changes</button>
        </div>
      </div>
    </form>

  </div>

app/views/user/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-3 profile-col">
        <img class="avatar" src="http://via.placeholder.com/48x48" alt="avatar">
        <h3><%= "#{@user.firstname} #{@user.lastname}" %></h3>

        <div class="panel panel-default">
          <div class="panel-heading">About Me</div>
          <div class="panel-body">
            <% if @user.bio %>
              <%= @user.bio %>
            <% else %>
              <%= link_to "Write something about yourself", edit_user_path(@user.id)  %>
            <% end %>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">Contact Info</div>
          <div class="panel-body"><%= @user.email %></div>
        </div>

        <%= link_to friends_path(@user.id) do %>
          <button class="btn btn-primary">See Friends</button>
        <% end %>
      </div>
      <div class="col-md-9 posts-col">
        <%= link_to "Create a post", new_post_path, class: 'btn btn-success btn-lg' %>

        <div class="posts">
          <% @posts.each do |post| %>
            <%= render 'posts/show', post: post, like: like(post.id) %>
          <% end %>
        </div>

      </div>
    </div>
  </div>