config/routes.rb
Rails.application.routes.draw do

  resources :friend_requests, only: [:create, :update, :destroy]
  resources :posts
  resources :comments, only: [:create]

  devise_for :user, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/users/all', to: 'user#all', as: :find_friends
  get '/users/:id', to: 'user#show', as: :user
  get '/users/:id/edit', to: 'user#edit', as: :edit_user
  get '/users/:id/friends', to: 'friends#index', as: :friends
  delete '/users/:id/friends', to: 'friends#destroy', as: :remove_friend

  post '/posts/like', to: 'likes#create', as: :like_post
  delete '/posts/:id/unlike', to: 'likes#destroy', as: :unlike_post

  get '/friend_requests/', to: 'friend_requests#index', as: :requests

  get '/privacy_policy', to: 'static_pages#privacy', as: :privacy

  match "*path", to: "application#render_404", via: :all

  devise_scope :user do
    authenticated :user do
      root 'static_pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { minimum: 1, maximum: 300 }

  belongs_to :user
  belongs_to :post
  has_many :notifications
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }
  validate :not_self

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  scope :saved, -> { where("id IS NOT NULL") }

  def accept
    user.friends << friend
    destroy
  end

  private
  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

  def not_friends
    errors.add(:friend, "is already added") if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, "already requested friendship") if friend.pending_friends.include?(user)
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }
  validate :not_self

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  private
  def create_inverse_relationship
    friend.friendships.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end
  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
# class Notification < ApplicationRecord
#   validates :activity, presence: true

#   belongs_to :user
# end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 500 }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :notifications
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: { maximum: 50 }
  validates :bio, length: { maximum: 300 }

  has_many :posts
  has_many :notifications
  has_many :likes
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friends

  def remove_friend
    current_user.friends.destroy(friend)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:success] = "Comment added successfully!"
      redirect_to Post.find(@comment.post_id)
    else
      flash.now[:error] = @comment.errors.messages
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: :destroy

  def index
    @friends = User.find(params[:id]).friends
  end

  def destroy
    current_user.remove_friend(@friend)
    head :no_content
  end

  private
  def set_friend
    @friend = current_user.friends.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.build(like_params)
    if @like.save
      redirect_back(fallback_location: authenticated_root_path)
    else
      flash.now[:danger] = 'Unable to like this post'
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @like.delete
    flash.now[:success] = 'Deleted'
    redirect_back(fallback_location: authenticated_root_path)
  end
  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts/1
  def show
    post
    @comment = Comment.new(post_id: params[:id])
    @comments = @post.comments.reverse
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    post
  end

  # POST /posts
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to authenticated_root_path
    else
      flash.now[:error] = @post.errors.messages
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    post
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    post
    authorize @post
    @post.destroy
    redirect_to authenticated_root_path, notice: 'Post was successfully destroyed.'
  end

  private

  def post
   @post ||= Post.find(params[:id])
   @like = @post.likes.where("user_id = ?", current_user.id).first
   return @post
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def all
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def bootstrap_class_for flash_type
    result = "alert "
    case flash_type.to_sym
      when :success
        result << "alert-success"
      when :error
        result << "alert-danger"
      when :alert
        result << "alert-warning"
      when :notice
        result << "alert-info"
      else
        result = flash_type
    end

    result
  end

  def friend_requests_count
    @incoming = FriendRequest.where(friend: current_user).length
  end

end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friendrequest_helper.rb
module FriendrequestHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def show_more
    true
  end
  def like(post_id)
    Post.find(post_id).likes.where("user_id = ?", current_user.id).first
  end
end

app/helpers/user_helper.rb
module UserHelper
  def others
    users = User.where.not(id: current_user.id)
  end

  def get_friend_request(user_id)
    FriendRequest.where("user_id = ? AND friend_id = ?", current_user.id, user_id).first || FriendRequest.new
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_show.html.erb
<div class="post">
  <div class="post-header">
  <%= link_to user_path(current_user.id) do %>
    <img class="avatar" src="http://via.placeholder.com/48x48" alt="avatar">
    <h3><%= "#{post.user.firstname} #{post.user.lastname}" %></h3>
    <!-- <% unless @hide_post_link %>
      <%= link_to "See More", post_path(post.id), class: "pull-right" %>
    <% end %> -->
  <% end %>
  </div>

  <div class="post-body">
    <p><%= post.content %></p>
  </div>

  <hr>
  <div class="post-footer">
    <div class="left-controls">
      <div class="footer-icon">
        <% if like.nil? %>
        <%= link_to like_post_path(like: {post_id: post.id}), method: :post do %>
          <i class="material-icons">thumb_up</i>
        <% end %>
        <% else %>
        <%= link_to unlike_post_path(like.id), method: :delete do %>
          <i class="material-icons liked">thumb_up</i>
        <% end %>
        <% end %>
        <span><%= post.likes.length %></span>
      </div>
      <div class="footer-icon">
        <%= link_to post_path(post.id), class: "pull-right" do %>
          <i class="material-icons">mode_comment</i>
        <% end %>
        <span><%= post.comments.length %></span>
      </div>
    </div>
    <div class="right-controls">
      <% if policy(post).update? %>
      <%= link_to edit_post_path(post.id) do %>
        <i class="material-icons">edit</i>
      <% end %>
      <% end %>
      <% if policy(post).destroy? %>
      <%= link_to post_path(post.id), method: :delete do %>
      <div class="footer-icon pull-right">
        <i id="delete-post" class="material-icons">delete</i>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container post-container">
  <div class="post-user">
    <img src="images/ic_account_box_black_24dp_2x.png" alt="">
    <h3><%= "#{@post.user.firstname} #{@post.user.lastname}" %></h3>
  </div>

  <%= form_for(@post, html: { class: 'form', method: "patch" }, url: post_path) do |f| %>
    <div class="form-group">
      <textarea placeholder="What's not on your mind?" class="form-control" rows="5" id="content" name="post[content]"><%= @post.content %></textarea>
    </div>
    <div>
      <%= link_to 'Back', authenticated_root_path, class:"btn btn-info" %>
      <button type="submit" class="btn btn-primary pull-right">Update</button>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="container post-container">
  <div class="post-user">
    <img src="images/ic_account_box_black_24dp_2x.png" alt="">
    <h3><%= "#{current_user.firstname} #{current_user.lastname}" %></h3>
  </div>

  <%= form_for(@post, html: { class: 'form' }, url: posts_path) do |f| %>
    <div class="form-group">
      <textarea placeholder="What's not on your mind?" class="form-control" rows="5" id="content" name="post[content]"></textarea>
    </div>
    <div>
      <%= link_to 'Back', authenticated_root_path, class:"btn btn-info" %>
      <button type="submit" class="btn btn-primary pull-right">Post</button>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<!-- main section -->
  <div class="container">

  <%= render 'posts/show', post: @post, like: @like %>

  <div class="post-comments">
    <!-- input field for a comment -->
    <div class="comment new" id="post-comment-form">
      <img src="http://via.placeholder.com/48x48" alt="">
      <%= form_for(@comment, html: { class: 'form-inline', method: 'post' }, url: comments_path) do |f| %>
        <%= f.hidden_field :post_id %>
        <input class="form-control" type="text" name="comment[content]" placeholder="add comment">
        <button class="btn btn-primary" type="submit">Comment</button>
      <% end %>
      <hr>
    </div>

    <!-- Regular comments -->
    <% @comments.each do |comment| %>
    <div class="comment">
    <%= link_to user_path(current_user.id) do %>
      <img class="avatar" src="http://via.placeholder.com/48x48" alt="avatar">
    <% end %>
      <p><%= comment.content %></p>
      <span class="comment-time"><%= time_ago_in_words(comment.created_at) << " ago" %></span>
      <hr>
    </div>
    <% end %>
  </div>
</div>