config/routes.rb
Rails.application.routes.draw do

  resources :friend_requests, only: [:create, :update, :destroy]
  resources :posts
  resources :comments, only: [:create]

  devise_for :user, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/users/all', to: 'user#all', as: :find_friends
  get '/users/:id', to: 'user#show', as: :user
  get '/users/:id/edit', to: 'user#edit', as: :edit_user
  get '/users/:id/friends', to: 'friends#index', as: :friends
  delete '/users/:id/friends', to: 'friends#destroy', as: :remove_friend

  post '/posts/like', to: 'likes#create', as: :like_post
  delete '/posts/:id/unlike', to: 'likes#destroy', as: :unlike_post

  get '/friend_requests/', to: 'friend_requests#index', as: :requests

  get '/privacy_policy', to: 'static_pages#privacy', as: :privacy

  match "*path", to: "application#render_404", via: :all

  devise_scope :user do
    authenticated :user do
      root 'static_pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { minimum: 1, maximum: 300 }

  belongs_to :user
  belongs_to :post
  has_many :notifications
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }
  validate :not_self

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  scope :saved, -> { where("id IS NOT NULL") }

  def accept
    user.friends << friend
    destroy
  end

  private
  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

  def not_friends
    errors.add(:friend, "is already added") if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, "already requested friendship") if friend.pending_friends.include?(user)
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }
  validate :not_self

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  private
  def create_inverse_relationship
    friend.friendships.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end
  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
# class Notification < ApplicationRecord
#   validates :activity, presence: true

#   belongs_to :user
# end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 500 }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :notifications
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: { maximum: 50 }
  validates :bio, length: { maximum: 300 }

  has_many :posts
  has_many :notifications
  has_many :likes
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friends

  def remove_friend
    current_user.friends.destroy(friend)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.build(like_params)
    if @like.save
      redirect_back(fallback_location: authenticated_root_path)
    else
      flash.now[:danger] = 'Unable to like this post'
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @like.delete
    flash.now[:success] = 'Deleted'
    redirect_back(fallback_location: authenticated_root_path)
  end
  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts/1
  def show
    post
    @comment = Comment.new(post_id: params[:id])
    @comments = @post.comments.reverse
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    post
  end

  # POST /posts
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to authenticated_root_path
    else
      flash.now[:error] = @post.errors.messages
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    post
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    post
    authorize @post
    @post.destroy
    redirect_to authenticated_root_path, notice: 'Post was successfully destroyed.'
  end

  private

  def post
   @post ||= Post.find(params[:id])
   @like = @post.likes.where("user_id = ?", current_user.id).first
   return @post
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def all
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def bootstrap_class_for flash_type
    result = "alert "
    case flash_type.to_sym
      when :success
        result << "alert-success"
      when :error
        result << "alert-danger"
      when :alert
        result << "alert-warning"
      when :notice
        result << "alert-info"
      else
        result = flash_type
    end

    result
  end

  def friend_requests_count
    @incoming = FriendRequest.where(friend: current_user).length
  end

end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/friendrequest_helper.rb
module FriendrequestHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def show_more
    true
  end
  def like(post_id)
    Post.find(post_id).likes.where("user_id = ?", current_user.id).first
  end
end

app/helpers/user_helper.rb
module UserHelper
  def others
    users = User.where.not(id: current_user.id)
  end

  def get_friend_request(user_id)
    FriendRequest.where("user_id = ? AND friend_id = ?", current_user.id, user_id).first || FriendRequest.new
  end
end

app/views/layouts/_navbar.html.erb
<nav>
  <div class="container">
    <% if user_signed_in? %>
    <%= link_to "Fakebook", authenticated_root_path, id: "logo", class: "logo-authenticated" %>
    <% else %>
    <%= link_to "Fakebook", unauthenticated_root_path, id: "logo" %>
    <% end %>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <div class="navbar-right">
        <div class="navbar-right-links">
          <%= link_to('Find Friends', find_friends_path) %>
          <%= link_to requests_path do %>
            <i class="material-icons">person_add</i>
            <span class="badge badge-danger"><%= friend_requests_count %></span>
          <% end %>

          <%= link_to user_path(current_user.id) do %>
            <img class="avatar" src="http://via.placeholder.com/48x48" alt="avatar">
          <% end %>
          <div class="nav-item dropdown">
            <i class="material-icons" id="dropdown-toggle">keyboard_arrow_down</i>
            <div id="dropdown-content" class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
            </div>
          </div>
        </div>
      </div>
      <% else %>
      <div class="navbar-right">
        <%= form_for(@user, html: { id: "log-in", class: "form-inline" }, url: session_path(@user)) do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', required: true %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, autocomplete: "off", class: 'form-control', required: true %>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Log In</button>
        <br>
        <% if devise_mapping.rememberable? -%>
        <div class="checkbox">
          <label><input type="checkbox" value="remember">Remember Me</label>
        </div>
        <% end %>
        <% end %>
      </div>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <% flash.each do |type, message| %>
        <div class="<%= bootstrap_class_for(type) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
      <% end %>
    </div>

    <!-- refactor later -->
    <%= yield %>

    <%= javascript_include_tag "http://code.jquery.com/jquery-3.3.1.min.js", 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js", 'data-turbolinks-track': 'reload' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>